In [1]:
import torch

In [4]:
x = torch.Tensor([4,3])
y = torch.Tensor([2,1])
print(x*y)

tensor([8., 3.])


In [5]:
x = torch.zeros([2,4])

In [6]:
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [7]:
x.shape

torch.Size([2, 4])

In [8]:
y = torch.rand([2,5])

In [15]:
y

tensor([[0.3263, 0.1546, 0.0957, 0.5336, 0.9360],
        [0.9166, 0.5995, 0.9574, 0.7846, 0.5451]])

In [17]:
y = y.view([5,2])

In [18]:
y

tensor([[0.3263, 0.1546],
        [0.0957, 0.5336],
        [0.9360, 0.9166],
        [0.5995, 0.9574],
        [0.7846, 0.5451]])